# Site settings

name: Sedgley Blog
author: Chris Sedgley
author_email: cbsedgley27@gmail.com
url: "http://sedgley.io"
permalink: pretty
title: "Sedgley.io"
description: "Personal blog about security realted topics"
keywords: "sedgley, security, wargames, technology, infosec, boo2root"
favicon: false

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

# me-img: "/img/me.jpg"
paginate: 15

paginate_path: "/blog/page:num"

post-preview-words: 128

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/cbsedgley"
  - title: "linkedin"
    url: "https://www.linkedin.com/pub/chris-sedgley/68/958/b4b"

404-img: false

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
